package com.example.rmsjims.data.schema

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Users(
    val id: Int? = null, // Auto-generated by database, null for inserts
    val email: String,
    val password: String,
    val role: String, // "admin", "staff", "assistant"
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null
)

